import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'media',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'Instrument Sans', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'IBM Plex Mono', 'monospace'],
        'display-lg': ['"Instrument Serif"', 'serif'],
        'display-lg-mobile': ['"Instrument Serif"', 'serif'],
        'headline-md': ['"Instrument Serif"', 'serif'],
        'article-body': ['Newsreader', 'Georgia', 'serif'],
        'article-body-mobile': ['Newsreader', 'Georgia', 'serif'],
        'ui-button': ['"Instrument Sans"', 'sans-serif'],
        'label-mono': ['"IBM Plex Mono"', 'monospace'],
        serif: ['"Instrument Serif"', 'serif'],
        newsreader: ['Newsreader', 'serif'],
      },
      spacing: {
        'margin-page': '24px',
        'gutter-ruler': '28px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      colors: {
        'ink-blue': '#2F2BC4',
        'graphite': '#5e5e63',
        'ink': '#16171B',
        'paper': '#F4F4F0',
        'paper-border': '#DFDFD7',
        'hairline': '#DFDFD7',
        'highlight-marker': '#ffdbd1',
        'surface-dim': '#dbd8e5',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2fe',
        'surface-container': '#efecf9',
        'surface-container-high': '#eae6f3',
        'surface-container-highest': '#e4e1ed',
        'on-surface': '#1b1b23',
        'on-surface-variant': '#464555',
        'outline-variant': '#c7c4d7',
        'primary-container': '#2f2bc4',
        'on-primary-container': '#adaeff',
        'tertiary-fixed': '#ffdbd1',
        'on-tertiary-fixed': '#3b0900',
        primary: {
          DEFAULT: '#6366f1',
          dark: '#4f46e5',
          light: '#818cf8',
        },
        secondary: {
          DEFAULT: '#10b981',
          dark: '#059669',
        },
        accent: '#f59e0b',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        muted: 'var(--muted)',
        border: 'var(--border)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        input: {
          DEFAULT: 'var(--input-bg)',
          text: 'var(--input-text)',
          placeholder: 'var(--input-placeholder)',
          border: 'var(--input-border)',
        },
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
  },
  plugins: [],
};

export default config;
